local _M = {
    _VERSION = '0.01',
    
    API_LOGIN = 'login',
    API_REG = 'reg',
    API_GUINFO = 'getuserinfo',
    API_AREAS = 'areas',
    API_CATEGORYS = 'categorys',
    API_GETGOOD = 'getgood',
    API_PUBGOOD = 'pubgood',
    API_GETGOODS = 'getgoods',
    API_SEARCH = 'search',
    API_TEST_CLEARTOKEN = 'testcleartoken',
    API_PUTCOMMENT = 'putcomment',
    API_GETCOMMENT = 'getcomment',
    API_PUTWISH = 'putwish',
    API_DELWISH = 'delwish',
    API_GETWISH = 'getwish',
	API_CHECKWISH = 'checkwish',
	API_UPFILE = 'upfile',
	API_DELIMG = "dimg",
	API_GETCOMNUMS = 'getcomnums',
	API_GETBANNER = 'getbanner',
	API_GETBESTGOODS = 'getbestgoods',
	API_SUBTIPOFF = 'subtipoff',
	API_GETSELLING_EXT = 'getselling_ext',
	API_GETWISH_EXT = "getwish_ext",
	API_GETUSERINFO_PUB = "getuserinfo_pub",
	API_CHANGEPASS = "changepass",
	API_CHANGEUSERINFO = "changeuserinfo",
	API_GETUSERPUBINFO = "getuserpubinfo",
	API_UPDATEPUBSTATUS = "updatepubstatus",
	API_GETRECLOGOS = 'getreclogos',
	API_UPDATEPUBCONTENT = 'updatepubcontent',
	API_GETCOUNT = 'getcount',
	API_GETMARQUEE = 'getmarquee',
	API_GETHOTGOODS = 'gethotgoods',
}

return _M
