module.exports = {
  '--font-size-22': '22px',
  '--font-size-18': '18px',
  '--font-size-16': '16px',
  '--font-size-15': '15px',
  '--font-size-14': '14px',
  '--font-size-13': '13px',
  '--font-size-12': '12px',
  '--font-size-11': '11px',
  '--font-size-10': '10px',

  '--font-family-medium': 'Helvetica Neue For Number,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFangSC-Medium,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif',
  '--font-family-light': 'Helvetica Neue For Number,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFangSC-Light,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif',

  '--color-white': '#FFF',
  '--color-red': '#FD4F57',
  '--color-gold': '#C2A67D',
  '--color-dark': '#222',
  '--color-black': '#000',
  '--color-blue': '#00B0FF',
  '--color-off-white': '#F5F5F5',
  '--color-light-grey': '#E5E5E5',
  '--color-medium-grey': '#CCC',
  '--color-dark-grey': '#888',
  '--color-green': '#1CD467',
  '--color-message': '#F1F1D4',
  '--color-success': '#33BD6B',
  '--color-alert': '#DFAE64',
  '--color-error': '#CC5367',
  '--btn-radius': '4px',
}